services:
  - type: web
    name: smartretailai
    env: python
    buildCommand: chmod +x deploy.sh && ./deploy.sh
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 4 --timeout 120
    envVars:
      - key: FLASK_APP
        value: app.py
      - key: FLASK_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DATABASE_URL
        fromDatabase:
          name: smartretailai-db
          property: connectionString

databases:
  - name: smartretailai-db
    databaseName: smartretailai
    user: smartretailai
    plan: free
    postgresMajorVersion: 15 